# Generated by Django 4.1.7 on 2023-05-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0017_auto_20200926_1459"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Question_Answer",
        ),
        migrations.DeleteModel(
            name="Suggestion",
        ),
        migrations.AlterField(
            model_name="artwork",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
