# Generated by Django 4.1.7 on 2023-05-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0018_delete_question_answer_delete_suggestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="wiki_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
