# Generated by Django 4.1.7 on 2023-09-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0019_artwork_wiki_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="artist",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="artwork",
            name="institution",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="artwork",
            name="material",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="artwork",
            name="size",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="artwork",
            name="time_period",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="image",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="thumb_image",
            field=models.CharField(max_length=200),
        ),
    ]
