# Generated by Django 4.1.7 on 2023-09-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "artworks",
            "0020_artwork_artist_artwork_institution_artwork_material_and_more",
        ),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="artwork",
        #     name="artist",
        # ),
        # migrations.RemoveField(
        #     model_name="artwork",
        #     name="institution",
        # ),
        # migrations.RemoveField(
        #     model_name="artwork",
        #     name="material",
        # ),
        # migrations.RemoveField(
        #     model_name="artwork",
        #     name="size",
        # ),
        # migrations.RemoveField(
        #     model_name="artwork",
        #     name="wiki_url",
        # ),
        migrations.AddField(
            model_name="artwork",
            name="location",
            field=models.CharField(default="Unknown", max_length=200),
        ),
        migrations.AddField(
            model_name="artwork",
            name="maker",
            field=models.CharField(default="Unknown", max_length=200),
        ),
        migrations.AddField(
            model_name="artwork",
            name="materials_and_techniques",
            field=models.CharField(default="Unknown", max_length=200),
        ),
        migrations.AddField(
            model_name="artwork",
            name="measurement",
            field=models.CharField(default="Unknown", max_length=200),
        ),
        migrations.AddField(
            model_name="artwork",
            name="subject",
            field=models.CharField(default="Unknown", max_length=200),
        ),
        migrations.AddField(
            model_name="artwork",
            name="type_of_object",
            field=models.CharField(default="Unknown", max_length=200),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="century",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="link",
            field=models.CharField(default="-", max_length=200),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="time_period",
            field=models.CharField(
                blank=True, default="Unknown", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="year",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
