# Generated by Django 4.1.7 on 2023-09-12 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0021_remove_artwork_artist_remove_artwork_institution_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artwork",
            name="artist",
        ),
        migrations.RemoveField(
            model_name="artwork",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="artwork",
            name="material",
        ),
        migrations.RemoveField(
            model_name="artwork",
            name="size",
        ),
        migrations.RemoveField(
            model_name="artwork",
            name="wiki_url",
        ),
    ]
