# Generated by Django 4.1.7 on 2023-09-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0022_remove_artwork_artist_remove_artwork_institution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="web_link",
            field=models.CharField(blank=True, default="-", max_length=200),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="century",
            field=models.CharField(default="Unknown", max_length=7),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="year",
            field=models.CharField(default="Unknown", max_length=7),
        ),
    ]
