# Generated by Django 4.1.7 on 2023-11-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0023_artwork_web_link_alter_artwork_century_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="web_link",
            field=models.CharField(blank=True, default="-", max_length=250),
        ),
    ]
