# Generated by Django 4.1.7 on 2024-05-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0026_alter_artwork_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="description_validated_by",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
