# Generated by Django 4.1.7 on 2024-09-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0028_metadata_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.artwork'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='weblink',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
    ]
