# Generated by Django 4.1.7 on 2024-09-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0029_alter_metadata_artwork_alter_metadata_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='type',
            field=models.CharField(choices=[('audio', 'Audio'), ('link', 'Link'), ('video', 'Video')], max_length=100),
        ),
    ]
